spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book1?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        jdbc:
          batch_size: 4
        order_updates: true
